replicaCount: 2

image:
  repository: ghcr.io/actions/gha-runner-scale-set-controller@sha256:3081ba15c41f0aa791058dedd2a7406fece24c9aeaa94956c268e5099427a452
  tag: ""

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8082"
  listenerEndpoint: "/metrics"

pprof:
  addr: ":6060"

flags:
  logLevel: info
  logFormat: json
  runnerMaxConcurrentReconciles: 4
  healthProbeBindAddress: ":8081"

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: gha-runner-scale-set-controller
